name: yuescript
title: Yuescript
base: core20
version: '0.15.14'
summary: A Moonscript dialect which compiles to Lua
description: |
  Yuescript is a Moonscript dialect. It is derived from Moonscript language 0.5.0 and continuously adopting new features to be more up to date.

  Moonscript is a language that compiles to Lua. Since original Moonscript has been used to write web framework lapis and run a few business web sites like itch.io and streak.club with some large code bases. The original language is getting too hard to adopt new features for those may break the stablility for existing applications.

  So Yuescript is a new code base for pushing the language to go forward and being a playground to try introducing new language syntax or programing paradigms to make Moonscript language more expressive and productive.
grade: stable
confinement: strict
license: MIT
icon: img/yuescript.svg
issues: https://github.com/pigpigyyy/Yuescript/issues
website: https://yuescript.org/
source-code: https://github.com/TheSignPainter98/yuescript-snap
contact: https://github.com/TheSignPainter98/yuescript-snap/issues

plugs:
  dot-luarocks:
    interface: personal-files
    read:
      - $HOME/.luarocks/share/lua
      - $HOME/.luarocks/lib/lua

apps:
  yue:
    command: usr/local/bin/yue
    plugs:
      - home
      - removable-media
      - dot-luarocks

parts:
  yuescript:
    source: https://github.com/pigpigyyy/Yuescript.git
    source-tag: v0.15.14
    source-depth: 1
    plugin: make
    override-pull: |
      snapcraftctl pull
      patch makefile $SNAPCRAFT_PROJECT_DIR/makefile.patch
    build-packages:
      - g++
